apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
        - name: bms
          image: prasanna394/bms-app:latest
          ports:
            - containerPort: 80   
          env:
            - name: NODE_ENV
              value: "production"

