apiVersion: v1
kind: Service
metadata:
  name: bms-service
spec:
  type: NodePort  
  selector:
    app: bms
  ports:
    - name: http
      port: 80        # Service port inside cluster
      targetPort: 80  # Container's exposed port
      nodePort: 30030 
